### ISSUE TITLE
Lots of errors in console in Safari

### ISSUE THREAD

**Issue by UdjinM6** [dashevo/proposal-generator#24]
This is just a few seconds after page finished loading:
![screen shot 2017-11-01 at 00 00 07](https://user-images.githubusercontent.com/1935069/32248795-d766b3ec-be97-11e7-9fb2-f873b00f399a.png)
And it keeps growing really fast.

As far as I can tell it's Safari only issue, works fine in Firefox for me.

**Comment by Alex-Werner** [comment]
@UdjinM6 Damn ! I'm not able to use Safari on Ubuntu (even using Wine, Apple stopped delivering Safari for windows). 

In the log of errors, does the first one is a `bad handshake method` ? Or, is there any other error you saw in these that the two I can read over there ?

(I might have a way to have access in 10+ days to a Mac, I will try to work on this at that time, but any pre-info could be very helpful).

Additionnaly, do you have errors when you go on : https://insight.dashevo.org ? 
I want to check if it's not because of different domain. Also can you test switching on testnet ?

**Comment by UdjinM6** [comment]
Here it is from the very beginning:
![screen shot 2017-11-01 at 07 25 42](https://user-images.githubusercontent.com/1935069/32260022-f9a92604-bed5-11e7-8ec3-d00393942c04.png)

This happens only when I switch to testnet, no errors while I stay on mainnet tab (but keeps spamming if I switch mainnet->testnet->mainnet).

PS. no, https://insight.dashevo.org/insight/ has no issues for me, however https://testnet-insight.dashevo.org/insight/ shows no errors but also no latest blocks.

**Comment by thephez** [comment]
FYI - I randomly happened to be doing a Testnet proposal today and think I observed the same thing (Chromium on Mint - basically Ubuntu). Everything worked but it seemed to take more than 6 blocks to return the `gobject submit` data.  Unfortunately, I wasn't paying close attention, but figured I'd pass on the info since I was not using Safari.

![dash_proposal_generator_error](https://user-images.githubusercontent.com/8145677/32286075-b14fe35c-bf02-11e7-91ab-94b8e737195a.png)

**Comment by UdjinM6** [comment]
btw, it looks like https://testnet-insight.dashevo.org/insight/ is out of sync (3000+ blocks behind)

**Comment by nmarley** [comment]
Thanks for reporting the testnet Insight issue This is an HA deployment, so it looks like one of the 2 nodes is out of sync:

```
$ curl -s https://testnet-insight.dashevo.org/insight-api-dash/status | jq .info.blocks
16343
$ curl -s https://testnet-insight.dashevo.org/insight-api-dash/status | jq .info.blocks
19962
$ curl -s https://testnet-insight.dashevo.org/insight-api-dash/status | jq .info.blocks
16343
$ curl -s https://testnet-insight.dashevo.org/insight-api-dash/status | jq .info.blocks
19962
```

Will fix now ^.

**Comment by UdjinM6** [comment]
Looks like this ^^^ fixed it. 👍
Closing

**Comment by Alex-Werner** [comment]
I sadly... don't get it

**Comment by UdjinM6** [comment]
I have no idea why either but there are no more errors for me :)
